name: Build (cross-platform)

on:
  push:
    branches:
      - ci-fix
  release:

jobs:
  build-linux:
    name: Build Linux
    uses: ./.github/workflows/build_linux.yml
    
  build-macos:
    name: Build macOS
    uses: ./.github/workflows/build_mac.yml

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Display structure of downloaded files
      run: ls -la artifacts/

    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/*/*/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}